# Generated by Django 5.2.11 on 2026-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('shows', models.PositiveIntegerField(default=1)),
                ('wristband_type', models.CharField(max_length=64)),
                ('upload_design', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('transport_per_band', models.DecimalField(decimal_places=2, default=0.4, max_digits=8)),
                ('wristbands_needed', models.PositiveIntegerField()),
                ('cost_per_band', models.DecimalField(decimal_places=2, max_digits=8)),
                ('band_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_guest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('white_label', models.BooleanField(default=False)),
                ('custom_skin', models.BooleanField(default=False)),
                ('delivery_to_venue', models.BooleanField(default=False)),
                ('upsell_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
