# Generated by Django 5.2.11 on 2026-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
