# Generated by Django 5.2.11 on 2026-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_checkoutrequest_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='amount_total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='currency',
            field=models.CharField(blank=True, default='eur', max_length=10),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='payment_status',
            field=models.CharField(blank=True, default='unpaid', max_length=40),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='stripe_customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
