# Generated by Django 5.2.11 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_newslettersignup_checkoutrequest_order_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutrequest",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="checkoutrequest",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="checkoutrequest",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="checkoutrequest",
            name="event_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="checkoutrequest",
            name="venue",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

