# Generated by Django 5.2.11 on 2026-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_checkoutrequest_client_info_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='event_date',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
