# Generated by Django 5.2.11 on 2026-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event_date_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='additional_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
